---
# tasks file for openssl-install
- name: Install openssl on CentOS 7
  block:
    - name: Install Dependencies
      ansible.builtin.yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - "@Development tools"
        - wget
        - make
        - tar
        - perl-IPC-Cmd
      become: yes
      tags:
        - openssl-dependencies

    - name: Create downloads directory
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/Downloads
        state: directory
        mode: '0755'

    - name: Download OpenSSL tar file with checksum (sha256) 
      block:
        - name: Get checksum (sha256) file
          ansible.builtin.uri:
            url: https://www.openssl.org/source/openssl-{{ openssl_version }}.tar.gz.sha256
            return_content: true
          register: checksum

        - name: Set checksum variable
          ansible.builtin.set_fact:
            openssl_checksum: "{{ checksum.content }}"

        - name: Download file and check
          ansible.builtin.get_url:
            url: https://www.openssl.org/source/openssl-{{ openssl_version }}.tar.gz
            dest: /home/{{ ansible_user }}/Downloads/openssl-{{ openssl_version }}.tar.gz
            checksum: sha256:{{ openssl_checksum }}
        
        - name: Unarchive tar
          ansible.builtin.unarchive:
            src: /home/{{ ansible_user }}/Downloads/openssl-{{ openssl_version }}.tar.gz
            dest: /home/{{ ansible_user }}/Downloads
            remote_src: yes
            creates: /home/{{ ansible_user }}/Downloads/openssl-{{ openssl_version }}

        - name: Show Checksum used
          ansible.builtin.debug:
            msg: "{{ openssl_checksum }}"
      when: ansible_facts['distribution'] == 'CentOS'
      tags:
        - openssl-download

    - name: Install downloaded OpenSSL
      block:
        - name: Run OpenSSL config
          ansible.builtin.command:
            chdir: /home/{{ ansible_user }}/Downloads/openssl-{{ openssl_version }}
            cmd: ./config
            creates: /home/{{ ansible_user }}/Downloads/openssl-{{ openssl_version }}/Makefile

        - name: Run Make command ( This takes a while. ~5 min )
          ansible.builtin.command:
            chdir: /home/{{ ansible_user }}/Downloads/openssl-{{ openssl_version }}
            cmd: make
            creates: /usr/local/bin/openssl
          become: yes

        - name: Run Make install command ( This takes a while. ~5 min )
          ansible.builtin.command:
            chdir: /home/{{ ansible_user }}/Downloads/openssl-{{ openssl_version }}
            cmd: make install
            creates: /usr/local/bin/openssl
          become: yes

        - name: Create symbolic link to new libssl & libcrypto
          ansible.builtin.file:
            src: /usr/local/lib64/{{ item }}
            dest: /usr/lib64/{{ item }}
            state: link
          become: yes
          with_items:
            - libssl.so.1.1
            - libcrypto.so.1.1

        - name: Remove old OpenSSL bin file
          ansible.builtin.file:
            path: /usr/bin/openssl
            state: absent
          become: yes

        - name: Create symbolic link to new bin
          ansible.builtin.file:
            src: /usr/local/bin/openssl
            dest: /usr/bin/openssl
            state: link 
          become: yes

      tags:
        - openssl-install
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
